package com.jobtrack;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import static org.junit.jupiter.api.Assertions.*;

public class DatabaseMigrationTests {

    private DataSource createTestDataSource(String dbName) {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:" + dbName + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    @Test
    public void testMigrationScenarioA_ExistingLegacyAdmin() throws Exception {
        DataSource ds = createTestDataSource("migration_scenario_a");

        // 1. Run migrations up to V2
        Flyway flyway = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("2")
                .load();
        flyway.migrate();

        // 2. Insert low-ID legacy user and high-ID legacy administrator (ID 142 > 100)
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO app_users (id, email, password_hash, role, enabled, created_at) " +
                    "VALUES (20, 'legacy_user@test.com', 'hash', 'ROLE_USER', true, NOW())");

            stmt.execute("INSERT INTO app_users (id, email, password_hash, role, enabled, created_at) " +
                    "VALUES (142, 'legacy_admin@test.com', 'hash', 'ROLE_ADMIN', true, NOW())");

            stmt.execute("INSERT INTO job_applications (company_name, job_title, status, date_applied, created_at, last_updated_at) " +
                    "VALUES ('Google', 'Software Engineer', 'APPLIED', '2026-08-12', NOW(), NOW())");
        }

        // 3. Migrate to V3
        Flyway flywayV3 = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("3")
                .load();
        flywayV3.migrate();

        // 4. Verify assertions
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            // Verify app_users is dropped
            assertThrows(Exception.class, () -> stmt.executeQuery("SELECT * FROM app_users"));

            // Verify both users are copied preserving their IDs
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM users WHERE id = 20")) {
                assertTrue(rs.next());
                assertEquals("legacy_user@test.com", rs.getString("username"));
            }
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM users WHERE id = 142")) {
                assertTrue(rs.next());
                assertEquals("legacy_admin@test.com", rs.getString("username"));
            }

            // Verify the application has been mapped to the admin (ID 142), NOT the user (ID 20)
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM job_applications")) {
                assertTrue(rs.next());
                assertEquals(142, rs.getLong("user_id"));
            }

            // Verify identity sequence synchronization (dynamic sequence reset)
            stmt.execute("ALTER TABLE users ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id) + 1, 1) FROM users)");

            // Insert a new user without providing id explicitly (sequence autogeneration)
            stmt.execute("INSERT INTO users (username, password_hash, role, enabled, demo_account, created_at) " +
                    "VALUES ('new_user@test.com', 'hash', 'ROLE_USER', true, false, NOW())");

            try (ResultSet rs = stmt.executeQuery("SELECT id FROM users WHERE username = 'new_user@test.com'")) {
                assertTrue(rs.next());
                long newId = rs.getLong("id");
                assertTrue(newId > 142, "Autogenerated ID should be strictly greater than max legacy ID (142), got: " + newId);
            }
        }
    }

    @Test
    public void testMigrationScenarioB_NoLegacyAdmin() throws Exception {
        DataSource ds = createTestDataSource("migration_scenario_b");

        // 1. Run migrations up to V2
        Flyway flyway = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("2")
                .load();
        flyway.migrate();

        // 2. Insert application without user
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO job_applications (company_name, job_title, status, date_applied, created_at, last_updated_at) " +
                    "VALUES ('Google', 'Software Engineer', 'APPLIED', '2026-08-12', NOW(), NOW())");
        }

        // 3. Migrate to V3
        Flyway flywayV3 = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("3")
                .load();
        flywayV3.migrate();

        // 4. Verify scenario B initial database state
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            // Verify fallback owner was created with ID = 1 and is disabled
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM users WHERE username = 'migration_placeholder'")) {
                assertTrue(rs.next());
                assertEquals(1, rs.getLong("id"));
                assertFalse(rs.getBoolean("enabled"));
                assertEquals("DISABLED_PLACEHOLDER_SENTINEL", rs.getString("password_hash"));
                assertFalse(rs.getBoolean("demo_account"));
            }

            // Verify application belongs to the fallback owner
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM job_applications")) {
                assertTrue(rs.next());
                assertEquals(1, rs.getLong("user_id"));
            }

            // Sync identity sequence before auto-generating ID for admin_prod to avoid conflicts
            stmt.execute("ALTER TABLE users ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id) + 1, 1) FROM users)");

            // 5. Simulate AdminUserSeeder execution & reassignment
            // Insert configured production admin
            stmt.execute("INSERT INTO users (username, password_hash, role, enabled, demo_account, created_at) " +
                    "VALUES ('admin_prod', 'bcrypt_hash', 'ROLE_USER', true, false, NOW())");

            long adminProdId = 0;
            try (ResultSet rs = stmt.executeQuery("SELECT id FROM users WHERE username = 'admin_prod'")) {
                assertTrue(rs.next());
                adminProdId = rs.getLong("id");
            }
            assertTrue(adminProdId > 1);

            // Reassign applications from placeholder (ID 1) to admin_prod
            stmt.execute("UPDATE job_applications SET user_id = " + adminProdId + " WHERE user_id = 1");

            // Delete placeholder from users
            stmt.execute("DELETE FROM users WHERE id = 1");

            // Verify placeholder no longer exists
            try (ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM users WHERE username = 'migration_placeholder'")) {
                assertTrue(rs.next());
                assertEquals(0, rs.getInt(1));
            }

            // Verify application now belongs to configured administrator
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM job_applications")) {
                assertTrue(rs.next());
                assertEquals(adminProdId, rs.getLong("user_id"));
            }
        }
    }

    @Test
    public void testMigrationScenarioC_MultipleAdminsFail() throws Exception {
        DataSource ds = createTestDataSource("migration_scenario_c");

        // 1. Run migrations up to V2
        Flyway flyway = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("2")
                .load();
        flyway.migrate();

        // 2. Insert two legacy administrators
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO app_users (id, email, password_hash, role, enabled, created_at) " +
                    "VALUES (1, 'admin1@test.com', 'hash', 'ROLE_ADMIN', true, NOW())");
            stmt.execute("INSERT INTO app_users (id, email, password_hash, role, enabled, created_at) " +
                    "VALUES (2, 'admin2@test.com', 'hash', 'ROLE_ADMIN', true, NOW())");
        }

        // 3. Migrate to V3 (should throw exception / fail division by zero)
        Flyway flywayV3 = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("3")
                .load();

        assertThrows(Exception.class, flywayV3::migrate, "Migration should fail due to multiple legacy administrators");
    }

    @Test
    public void testMigrationScenarioD_ZeroAdminsFail() throws Exception {
        DataSource ds = createTestDataSource("migration_scenario_d");

        // 1. Run migrations up to V2
        Flyway flyway = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("2")
                .load();
        flyway.migrate();

        // 2. Insert legacy users but NO admin
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO app_users (id, email, password_hash, role, enabled, created_at) " +
                    "VALUES (1, 'user1@test.com', 'hash', 'ROLE_USER', true, NOW())");
        }

        // 3. Migrate to V3 (should throw exception / fail division by zero)
        Flyway flywayV3 = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("3")
                .load();

        assertThrows(Exception.class, flywayV3::migrate, "Migration should fail due to zero legacy administrators while legacy users exist");
    }

    @Test
    public void testMigrationScenarioE_NoUsersNoApplicationsNoPlaceholder() throws Exception {
        DataSource ds = createTestDataSource("migration_scenario_e");

        // 1. Run migrations up to V2
        Flyway flyway = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("2")
                .load();
        flyway.migrate();

        // 2. Database remains completely empty (no legacy users, no applications)

        // 3. Migrate to V3
        Flyway flywayV3 = Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .target("3")
                .load();
        flywayV3.migrate();

        // 4. Verify no placeholder user was created
        try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
            try (ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM users")) {
                assertTrue(rs.next());
                assertEquals(0, rs.getInt(1), "No users should exist since there were no applications or legacy records to map");
            }
        }
    }
}
