-- V1__baseline_schema.sql

CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    job_url VARCHAR(255),
    date_applied DATE,
    status VARCHAR(255) NOT NULL,
    stage VARCHAR(255),
    recruiter_email VARCHAR(255),
    notes TEXT,
    source VARCHAR(255),
    company_career_url VARCHAR(255),
    salary_range VARCHAR(255),
    priority VARCHAR(255),
    follow_up_date DATE,
    deadline_date DATE,
    job_description TEXT,
    job_description_summary TEXT,
    original_job_url VARCHAR(255),
    match_score INTEGER,
    matched_skills TEXT,
    missing_skills TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_application_id BIGINT NOT NULL,
    from_status VARCHAR(255),
    to_status VARCHAR(255) NOT NULL,
    changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    note VARCHAR(255),
    CONSTRAINT fk_status_history_application FOREIGN KEY (job_application_id) REFERENCES job_applications(id) ON DELETE CASCADE
);

CREATE TABLE application_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_application_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    document_type VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_application_documents_application FOREIGN KEY (job_application_id) REFERENCES job_applications(id) ON DELETE CASCADE
);

CREATE INDEX idx_status_history_application ON status_history(job_application_id);
CREATE INDEX idx_application_documents_application ON application_documents(job_application_id);
