-- V3__auth_and_ownership.sql

-- 1. Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    role VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    demo_account BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- 2. Copy existing legacy user records preserving IDs and identities
INSERT INTO users (id, username, password_hash, display_name, role, enabled, demo_account, created_at)
SELECT id, email, password_hash, email, role, enabled, FALSE, created_at FROM app_users;

-- 3. Fail migration if legacy users exist but there is NOT exactly one administrator (role = 'ROLE_ADMIN')
SELECT 1 / (CASE WHEN (SELECT COUNT(*) FROM app_users) > 0 AND (SELECT COUNT(*) FROM app_users WHERE role = 'ROLE_ADMIN') <> 1 THEN 0 ELSE 1 END);

-- 4. Add user_id column as nullable first to job_applications
ALTER TABLE job_applications ADD COLUMN user_id BIGINT;

-- 5. Scenario A: Backfill existing applications mapping to the EXACT migrated legacy production administrator (role = 'ROLE_ADMIN')
UPDATE job_applications
SET user_id = (
    SELECT id FROM users
    WHERE username = (
        SELECT email FROM app_users
        WHERE role = 'ROLE_ADMIN'
    )
)
WHERE user_id IS NULL AND EXISTS (SELECT 1 FROM app_users);

-- 6. Scenario B: If no legacy user existed and at least one orphaned application exists, seed one disabled migration placeholder owner user with ID 1
INSERT INTO users (id, username, password_hash, display_name, role, enabled, demo_account, created_at)
SELECT 1, 'migration_placeholder', 'DISABLED_PLACEHOLDER_SENTINEL', 'Migration Placeholder', 'ROLE_USER', false, false, NOW()
WHERE NOT EXISTS (SELECT 1 FROM users)
  AND EXISTS (SELECT 1 FROM job_applications WHERE user_id IS NULL);

-- 7. Assign any remaining orphaned applications to the placeholder owner if it was created
UPDATE job_applications
SET user_id = (SELECT id FROM users WHERE username = 'migration_placeholder')
WHERE user_id IS NULL AND EXISTS (SELECT 1 FROM users WHERE username = 'migration_placeholder');

-- 8. Drop the old app_users table
DROP TABLE app_users;

-- 9. Enforce NOT NULL constraint on user_id
ALTER TABLE job_applications ALTER COLUMN user_id SET NOT NULL;

-- 10. Enforce foreign key constraint
ALTER TABLE job_applications
ADD CONSTRAINT fk_job_applications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- 11. Enforce user_id index
CREATE INDEX IF NOT EXISTS idx_job_applications_user_id ON job_applications(user_id);
